server:
  port: 8084

management:
 endpoints:
   web:
     exposure:
       include: "*"


spring:
  application:
    name: ApiGateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # Event Service
            - id: event-service
              uri: lb://EVENT-SERVICE
              predicates:
                - Path=/events/**

            # Registration Service
            - id: registration-service
              uri: lb://REGISTRATION-SERVICE
              predicates:
                - Path=/registrations/**

            # Review Service
            - id: review-service
              uri: lb://REVIEW-SERVICE
              predicates:
                - Path=/reviews/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
