server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.cloud.stream.kafka.binder.brokers=localhost:9092

spring.cloud.stream.bindings.eventCreatedConsumer-in-0.destination=event-created-events
spring.cloud.stream.bindings.eventCreatedConsumer-in-0.group=registration-service
spring.cloud.stream.bindings.eventCreatedConsumer-in-0.content-type=application/json

spring.cloud.stream.bindings.eventUpdatedConsumer-in-0.destination=event-updated-events
spring.cloud.stream.bindings.eventUpdatedConsumer-in-0.group=registration-service
spring.cloud.stream.bindings.eventUpdatedConsumer-in-0.content-type=application/json

spring.cloud.function.definition=eventCreatedConsumer,eventUpdatedConsumer

# Logging
logging.level.org.springframework.integration=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.kafka=DEBUG

# DB
spring.datasource.url=jdbc:h2:file:./data/registrationdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
