server.port=8082
spring.application.name=REGISTRATIONSERVICE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# RabbitMQ (auto-connects to localhost:5672)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Input bindings (queues will be auto-created)
spring.cloud.stream.bindings.eventCreatedConsumer-in-0.destination=event-created-events
spring.cloud.stream.bindings.eventCreatedConsumer-in-0.group=registration-service
spring.cloud.stream.bindings.eventCreatedConsumer-in-0.content-type=application/json

spring.cloud.stream.bindings.eventUpdatedConsumer-in-0.destination=event-updated-events
spring.cloud.stream.bindings.eventUpdatedConsumer-in-0.group=registration-service
spring.cloud.stream.bindings.eventUpdatedConsumer-in-0.content-type=application/json

# DB & logging
spring.datasource.url=jdbc:h2:file:./data/registrationdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

logging.level.be.pxl.services.registrationservice=DEBUG
