server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.stream.kafka.binder.brokers=localhost:9092

# Input binding for EventCreatedEvent
spring.cloud.stream.bindings.eventCreatedConsumer-in-0.destination=event-created-events
spring.cloud.stream.bindings.eventCreatedConsumer-in-0.group=registration-service
spring.cloud.stream.bindings.eventCreatedConsumer-in-0.content-type=application/json

# Input binding for EventUpdatedEvent
spring.cloud.stream.bindings.eventUpdatedConsumer-in-0.destination=event-updated-events
spring.cloud.stream.bindings.eventUpdatedConsumer-in-0.group=registration-service
spring.cloud.stream.bindings.eventUpdatedConsumer-in-0.content-type=application/json
